version: '3.4'

services:
  mdrive.server.api:
    container_name: mdrive-server-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8100:8080"
    restart: always
    volumes:
      - /data/mdrive-server-api/appsettings.json:/app/appsettings.json:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"