name: Release Windows CI

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run:  cd scripts && .\build.ps1
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MDrive
        path: 
          .\scripts\MDrive.zip
